### ISSUE TITLE
Export works, Import doesn't work

### ISSUE THREAD

**Issue by jomeier** [ansible/tower-cli#581]
Hi,

today I tried out the export / import feature of tower-cli.

I installed the latest awx version on my machine. I started it and waited until it was accessible through the web ui. I logged in.

On the command line I exported all settings like this:
```
tower-cli receive --all > test.json
```

__test.json__ was filled with data.

Afterwards I imported this data again to the same instance of AWX like this:
```
tower-cli send test.json
```

I get this error message:
```
Asset of type user is missing identifier field username
Error: One or more errors encountered in provided assets, stopping import
```

I appended the test.json file.

Best regards,

Josef

[test.txt](https://github.com/ansible/tower-cli/files/2259554/test.txt)

**Comment by jomeier** [comment]
Why are the user names not exported? 

Lot's of objects are connected to a certain user. If they are not known to tower, the import will not work at all.

**Comment by john-westcott-iv** [comment]
@jomeier, This is strange behavior. In the version information you listed, is that the server you are exporting out of, importing into, or both? The user is correctly exported for me (see below) so I want to check using the same versions as you. Also, can you try to download and build tower-cli from source to see if you are still getting the same issue.

```
tower-cli receive --user admin --tower-host http://localhost:8081
[
  {
    "username": "admin", 
    "first_name": "", 
    "last_name": "", 
    "email": "admin@example.com", 
    "is_superuser": true, 
    "asset_type": "user"
  }
]
```

**Comment by jomeier** [comment]
A fresh installation of AWX V1.0.7.2 shows the same behaviour. 

```
tower-cli receive --user admin
```

```
[
  {
    "asset_type": "user"
  }
]
```

**Comment by lwm** [comment]
Also seeing this on a fresh `pip install ansible-tower-cli` and latest docker awx setup.

**Comment by jomeier** [comment]
This is my PR which exports more user attributes. Makes the import work again.

https://github.com/ansible/tower-cli/pull/586

**Comment by srgvg** [comment]
Seems like a bug in AWX API, which I myself noticed in 1.0.8 and that seems fixed in 2.0.1?

see for more details:
https://github.com/ansible/tower-cli/pull/586#issuecomment-432176155

**Comment by tumluliu** [comment]
For my data migration from awx 2.0.1 to 9.1.0 with tower-cli 3.3.7, this issue still exists

**Comment by TwoTwenty** [comment]
> For my data migration from awx 2.0.1 to 9.1.0 with tower-cli 3.3.7, this issue still exists

I am in the same boat still to with similar versions. 
AWX 2.1.2.0
tower-cli 3.3.8
